---
logLevel: WARN
submissionsBase: http://submissions.agileaustralia.com.au/
signInPath: users/sign_in
itemPath: proposals/
email: login@example.com
password: someCred5
channelMapping:
    15: https://hooks.slack.com/services/.../.../...
